// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfkrgvoymxffuuvcdghb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNma3Jndm95bXhmZnV1dmNkZ2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODg3NTcsImV4cCI6MjA2NDc2NDc1N30.B728mS8menPvuojLYVawKo_Pb09KBoQlBPR1Brc1ig8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);